import type { Language } from '@/hooks/use-language'
export type Copy = Record<Language, string>
const c = (ru: string, en: string): Copy => ({ ru, en })
const work = (ru: string, en: string, textRu: string, textEn: string) => ({ title: c(ru, en), text: c(textRu, textEn) })

export const CASES = [
  {
    id: 'scrum', category: c('Управление командой', 'Team operations'), nav: c('Проектная система', 'Project system'),
    title: c('Перестройка проектной системы отдела дизайна и контента', 'Rebuilding the project system for design and content'),
    intro: c('Спроектировала и внедрила новый способ проектной работы команды: структуру задач, двухнедельные спринты, регулярные встречи, контроль загрузки, сроков и зависимостей.', 'Designed and introduced a new way of managing team projects: task structure, two-week sprints, regular meetings, capacity, deadlines and dependencies.'),
    outcome: c('В одном спринте держу в фокусе около 150 задач: сроки, ответственных, приоритеты и зависимости. После изменений в операционной модели отдела объём выполняемых задач вырос примерно на 20%, а доля просроченных снизилась на 40%.', 'I keep around 150 tasks in focus within a sprint: deadlines, owners, priorities and dependencies. Following changes to the department’s operating model, completed task volume grew by about 20% and the share of overdue tasks fell by 40%.'),
    metrics: [
      { value: c('≈150', '≈150'), label: c('задач в фокусе спринта', 'tasks in focus per sprint') },
      { value: c('−40%', '−40%'), label: c('доля просроченных задач', 'share of overdue tasks') },
      { value: c('+20%', '+20%'), label: c('объём выполняемых задач', 'completed task volume') },
    ],
    context: c('Большое количество параллельных задач по новым продуктам, дизайну, упаковке, инструкциям, контенту, видео и локализации требовало единой системы управления.', 'Parallel work on new products, design, packaging, manuals, content, video and localisation needed a shared management system.'),
    role: c('Самостоятельно спроектировала и внедрила новую логику проектной работы отдела, а после успешного внедрения масштабировала подход на команду e-commerce.', 'Independently designed and introduced the department’s new project workflow, then extended the approach to the e-commerce team after successful implementation.'),
    changes: [
      work('Структура задач', 'Task structure', 'Сформировала единые правила декомпозиции: материнские задачи, подзадачи, ответственные, сроки, зависимости и ожидаемый результат.', 'Defined shared task-breakdown rules: parent tasks, subtasks, owners, deadlines, dependencies and expected outcomes.'),
      work('Спринты и работа команды', 'Sprints and teamwork', 'Внедрила двухнедельные спринты и регулярный ритм работы: планирование спринта, ежедневную синхронизацию и ретроспективу. Выполняю функции Scrum Master.', 'Introduced two-week sprints, sprint planning, daily coordination and retrospectives. I perform Scrum Master duties.'),
      work('Контроль исполнения', 'Delivery tracking', 'Подготовила инструкции, реестр задач, систему регулярных уведомлений и управленческие сводки по ближайшим дедлайнам и рискам.', 'Created instructions, a task register, recurring notifications and management summaries of upcoming deadlines and risks.'),
      work('Ресурсы и загрузка', 'Resources and capacity', 'Работала с оценкой трудоёмкости, загрузкой команды и распределением функций в рамках операционной модели отдела.', 'Worked on effort estimates, team capacity and allocation of responsibilities within the department’s operating model.'),
      work('Масштабирование в e-commerce', 'Expansion to e-commerce', 'После внедрения системы в отделе дизайна и контента с нуля выстроила работу e-commerce-команды по Agile: спринты, приоритизация, разбор задач и регулярные встречи.', 'After implementing the system in design and content, built the e-commerce team’s Agile workflow from scratch: sprints, prioritisation, task clarification and recurring meetings.'),
    ],
    result: c('Отдел работает по единой структуре задач и спринтов; подход масштабирован на e-commerce. Изменения операционной модели сопровождались ростом объёма выполняемых задач примерно на 20% и снижением доли просроченных на 40%. Эти показатели относятся к операционной модели в целом.', 'The department uses a shared task and sprint structure, and the approach was extended to e-commerce. Changes to the operating model were accompanied by about 20% growth in completed task volume and a 40% reduction in the overdue share. These figures refer to the overall operating model.'),
    tags: ['Bitrix24 Scrum Pro', 'Scrum', 'Agile', 'Facilitation', 'Capacity Planning', 'Process Design'],
  },
  {
    id: 'video', category: c('Экономика и аналитика', 'Economics and analysis'), nav: c('Видеопроизводство', 'Video production'),
    title: c('Экономика и модель собственного видеопроизводства', 'Economics and model for in-house video production'),
    intro: c('Выявила высокую стоимость внешнего производства видеоконтента, рассчитала альтернативную модель и подготовила бизнес-кейс собственного видеопроизводства.', 'Identified the high cost of outsourced video production, calculated an alternative model and prepared a business case for in-house production.'),
    outcome: c('Проанализировала внешний пул затрат объёмом 5,4 млн ₽ и разработала модель стоимостью около 1,7 млн ₽. Расчётный потенциал снижения затрат — до 69%. После финансовой модели перешла к проработке инфраструктуры, ресурсов и сценария запуска.', 'Analysed an external cost pool of RUB 5.4 million and developed a model costing around RUB 1.7 million, with potential cost reduction of up to 69%. Then moved on to infrastructure, resources and a launch scenario.'),
    metrics: [
      { value: c('5,4 млн ₽', 'RUB 5.4M'), label: c('анализируемый внешний пул затрат', 'external cost pool analysed') },
      { value: c('1,7 млн ₽', 'RUB 1.7M'), label: c('расчётная модель', 'proposed cost model') },
      { value: c('до −69%', 'up to −69%'), label: c('потенциальное снижение затрат', 'potential cost reduction') },
      { value: c('7', '7'), label: c('вариантов площадок изучено', 'potential locations examined') },
    ],
    note: c('Расчётный потенциальный эффект, а не уже полученная экономия.', 'Projected potential impact, not realised savings.'),
    context: c('Стоимость производства единицы видеоконтента через внешних исполнителей была высокой. Нужно было понять, при каких условиях внутреннее производство станет экономически целесообразным.', 'The cost per video produced by external suppliers was high. The task was to establish when in-house production would become economically viable.'),
    role: c('Самостоятельно провела анализ, построила финансовую и ресурсную модель и довела проект до предпроектной проработки инфраструктуры.', 'Independently conducted the analysis, built the financial and resource model and took the project through preliminary infrastructure planning.'),
    changes: [
      work('Анализ экономики', 'Economic analysis', 'Собрала текущие затраты и сравнила несколько сценариев организации видеопроизводства.', 'Compiled current costs and compared several ways of organising video production.'),
      work('Ресурсная модель', 'Resource model', 'Просчитала необходимые роли, загрузку, постоянные и переменные расходы, мощность производства и требования к инфраструктуре.', 'Calculated required roles, workload, fixed and variable expenses, production capacity and infrastructure needs.'),
      work('Исследование внутренних практик', 'Internal practice research', 'Собрала информацию о подразделениях компании, которые уже работают с видеопроизводством, и использовала её при формировании требований.', 'Researched company departments already producing video and used the findings to define requirements.'),
      work('Студия и модель использования', 'Studio and utilisation model', 'Подготовила требования к помещению и оборудованию, участвовала в осмотрах и сравнении семи площадок. Проработала совместное использование студии несколькими подразделениями и модель загрузки.', 'Defined space and equipment requirements, took part in site visits and compared seven locations. Developed shared-use scenarios across departments and a utilisation model.'),
      work('Управленческое решение', 'Management decision support', 'Собрала анализ, расчёты, риски и варианты реализации в консолидированную презентацию для собственников компании.', 'Consolidated analysis, calculations, risks and implementation options into a presentation for the company owners.'),
    ],
    result: c('Подготовила бизнес-кейс с финансовой и ресурсной моделью, требованиями к инфраструктуре и вариантами запуска. Проект дошёл до предпроектной проработки; снижение затрат до 69% остаётся расчётным потенциальным эффектом.', 'Delivered a business case with financial and resource models, infrastructure requirements and launch options. The project reached preliminary planning; the reduction of up to 69% remains a projected potential effect.'),
    tags: ['Excel / Google Sheets', 'Financial Modelling', 'Business Analysis', 'Resource Planning', 'Production', 'PowerPoint'],
  },
  {
    id: 'tender', category: c('Подрядчики и коммерческая работа', 'Vendors and commercial work'), nav: c('Production-тендер', 'Production tender'),
    title: c('Тендер среди 20+ production-компаний', 'A tender involving 20+ production companies'),
    intro: c('Организовала системный отбор production-партнёра: от исследования рынка и единых требований до переговоров, тестовых работ и сравнительного анализа.', 'Organised a structured production-partner selection process, from market research and shared requirements to negotiations, test assignments and comparative analysis.'),
    outcome: c('Сформировала пул из более чем 20 компаний и единый процесс оценки, чтобы предложения можно было сравнивать по одинаковым требованиям, стоимости, срокам и результату тестовых работ.', 'Built a pool of more than 20 companies and a consistent evaluation process, making proposals comparable against shared requirements, costs, timelines and test results.'),
    metrics: [
      { value: c('20+', '20+'), label: c('компаний в пуле', 'companies in the pool') },
      { value: c('КП → переговоры → тесты', 'Proposals → talks → tests'), label: c('единый процесс отбора', 'a shared selection process') },
      { value: c('Единые критерии', 'Shared criteria'), label: c('для сравнительного решения', 'for a comparative decision') },
    ],
    context: c('Нужно было изучить рынок и подготовить структурированную основу для выбора production-партнёра.', 'The task was to research the market and prepare a structured basis for selecting a production partner.'),
    role: c('Вела операционную часть тендера и собирала информацию, необходимую для принятия решения.', 'Managed the operational side of the tender and gathered the information needed for a decision.'),
    changes: [
      work('Исследование рынка', 'Market research', 'Сформировала пул из 20+ потенциальных исполнителей.', 'Built a pool of 20+ potential suppliers.'),
      work('Единые требования', 'Shared requirements', 'Подготовила вводные и требования, чтобы коммерческие предложения можно было корректно сравнивать между собой.', 'Prepared briefs and requirements so commercial proposals could be compared consistently.'),
      work('Коммуникация и переговоры', 'Communication and negotiation', 'Координировала взаимодействие, собирала предложения и участвовала в переговорах.', 'Coordinated communication, collected proposals and participated in negotiations.'),
      work('Тестовые проекты', 'Test assignments', 'Организовывала тестовые работы и сбор результатов.', 'Organised test assignments and collected the results.'),
      work('Сравнительный анализ', 'Comparative analysis', 'Структурировала стоимость, условия, сроки и результаты тестов в материалы для принятия управленческого решения.', 'Structured costs, terms, timelines and test results into materials for a management decision.'),
    ],
    result: c('Создала единый процесс оценки и сравнительные материалы по предложениям компаний. Подготовила основу для выбора партнёра по согласованным требованиям и результатам тестовых работ.', 'Created a consistent evaluation process and comparative proposal materials, providing a basis for partner selection using agreed requirements and test results.'),
    tags: ['Vendor Management', 'Procurement', 'Negotiations', 'Comparative Analysis', 'Production', 'Project Coordination'],
  },
  {
    id: 'erp', category: c('Бизнес-анализ и корпоративный IT', 'Business analysis and enterprise IT'), nav: c('ERP-календарь', 'ERP calendar'),
    title: c('Проектирование производственного календаря в ERP', 'Designing a production calendar within an ERP system'),
    intro: c('Участвовала в проектировании и внедрении корпоративного производственного календаря: от описания бизнес-процессов и BPMN до прототипа интерфейса и корректировок продукта на этапе разработки.', 'Contributed to designing and implementing an enterprise production calendar, from business processes and BPMN to an interface prototype and product refinements during development.'),
    outcome: c('Перевела реальные процессы своих подразделений в требования к ERP-системе, создала собственный прототип календаря и работала над решением вместе с аналитиками и программистами. Часть логики и интерфейсных решений из прототипа вошла в реализованный продукт.', 'Translated my departments’ actual workflows into ERP requirements, created a calendar prototype and worked with analysts and developers on the solution. Some workflow and interface ideas from the prototype were used in the implemented product.'),
    metrics: [
      { value: c('BPMN', 'BPMN'), label: c('описание бизнес-процессов', 'business process modelling') },
      { value: c('ERP', 'ERP'), label: c('корпоративная система', 'enterprise system') },
      { value: c('Прототип → реализация', 'Prototype → implementation'), label: c('часть решений вошла в продукт', 'some solutions adopted in the product') },
    ],
    context: c('Для корпоративной ERP-системы разрабатывался производственный календарь, который должен был учитывать реальные процессы, сроки, зависимости, загрузку и особенности работы разных подразделений.', 'The enterprise ERP production calendar needed to reflect real processes, deadlines, dependencies, capacity and the working practices of different departments.'),
    role: c('Представляла бизнес-логику своих направлений и активно участвовала в проектировании продукта на этапах анализа, разработки и внедрения.', 'Represented the business logic of my areas and actively contributed during analysis, development and implementation.'),
    changes: [
      work('Бизнес-процессы', 'Business processes', 'Уточняла процессы своих подразделений и самостоятельно формировала BPMN-карты отдельных процессов.', 'Clarified departmental workflows and independently created BPMN maps for individual processes.'),
      work('Требования к системе', 'System requirements', 'Передавала команде разработки новые вводные, сценарии использования, ограничения и реальные рабочие кейсы.', 'Supplied the development team with new inputs, use cases, constraints and real working scenarios.'),
      work('Прототип', 'Prototype', 'Самостоятельно создала прототип производственного календаря: структуру информации, логику работы и интерфейсные решения.', 'Independently created a production calendar prototype covering information structure, workflow and interface design.'),
      work('Работа с разработкой', 'Working with developers', 'На этапах реализации давала корректировки по логике и интерфейсу системы, обсуждала новые версии и уточняла требования.', 'Provided workflow and interface corrections during implementation, discussed new versions and refined requirements.'),
      work('Внедрение решений', 'Implementation of ideas', 'Часть идей и решений из моего прототипа была использована программистами при создании производственного календаря.', 'Developers used some ideas and solutions from my prototype when building the production calendar.'),
    ],
    result: c('Бизнес-процессы переведены в требования и прототип. Часть предложенной логики и интерфейсных решений использована в реализованном календаре; мой вклад — бизнес-анализ, проектирование и работа с командой разработки.', 'Business processes were translated into requirements and a prototype. Some proposed workflow and interface solutions were adopted in the implemented calendar; my contribution covered business analysis, design and collaboration with the development team.'),
    tags: ['ERP', 'BPMN', 'Business Analysis', 'Process Mapping', 'Prototyping', 'Cross-functional Collaboration'],
  },
] as const

export const MORE_PROJECTS = [
  { id: 'automation', title: c('20+ внутренних инструментов и автоматизаций', '20+ internal tools and automations'),
    text: c('Разработала более 20 инструментов для коллег и руководителей: сводки, реестры, расчёты, планирование, заявки, контроль сроков и уведомления. Использовала Google Sheets, Apps Script и Bitrix24 — от постановки задачи и логики до тестирования и рабочего решения.', 'Built over 20 tools for colleagues and managers: summaries, registers, calculations, planning, requests, deadlines and notifications. Used Google Sheets, Apps Script and Bitrix24, from defining the problem and logic through testing to a working solution.'),
    facts: [c('20+ рабочих решений', '20+ working solutions')] },
  { id: 'kpi', title: c('KPI-системы', 'KPI systems'),
    text: c('С нуля разработала KPI-системы для отдела дизайна и контента и складского блока: управляемые показатели, формулы и источники данных. Для склада изучила автоматическое получение данных из ERP и создала инструменты расчёта и отчётности. Ещё в двух KPI-проектах участвовала в создании расчётов и автоматизации.', 'Built KPI systems for design and content and for warehouse operations: controllable metrics, formulas and data sources. For the warehouse, researched automated ERP data retrieval and created calculation and reporting tools. Supported calculations and automation in two further KPI projects.'),
    facts: [c('2 системы с нуля', '2 systems built from scratch'), c('+2 проекта с моей поддержкой', '+2 projects supported')] },
  { id: 'launch', title: c('Подготовка и локализация продуктов', 'Product preparation and localisation'),
    text: c('Координирую материалы для зарубежных рынков: приоритеты, зависимости, трудоёмкость, ресурсы и готовность. Работа включает локализацию на русский, английский и китайский и синхронизацию product, operations, design, content и production.', 'Coordinate assets for international markets: priorities, dependencies, effort, resources and readiness. This includes Russian, English and Chinese localisation and coordination across product, operations, design, content and production.'),
    facts: [c('≈10 моделей в подготовке', '≈10 models in preparation')] },
  { id: 'dealers', title: c('Сайт для иностранных дилеров', 'Website for international dealers'),
    text: c('Собрала и структурировала информацию для будущих иностранных партнёров, подготовила содержание страницы и согласовала его внутри компании. Довела проект от бизнес-задачи и структуры материалов до готовой страницы и участвовала в публикации на зарубежной инфраструктуре.', 'Collected and structured information for prospective international partners, prepared the page content and coordinated internal approval. Took the project from business needs and content structure to a finished page and helped publish it on international infrastructure.'),
    facts: [c('От бизнес-задачи до публикации', 'From business needs to publication')] },
  { id: 'storage', title: c('Архитектура внутреннего хранилища', 'Internal storage architecture'),
    text: c('Пересобрала структуру папок, именование, ответственность, права доступа, передачу и архивирование материалов. Продумала переход так, чтобы сохранить рабочие ссылки и взаимодействие внутренних команд и подрядчиков.', 'Rebuilt folder structure, naming, ownership, permissions, handoffs and archiving. Planned the transition to preserve working links and collaboration between internal teams and contractors.'),
    facts: [c('Переход с сохранением рабочих ссылок', 'A transition preserving working links')] },
] as const
