import { delay, translate } from './scene-utils'
import { useState } from 'react'
import { Check, ClipboardList, FileCheck2, GitPullRequest, Handshake, Network, Search, Send, Settings2 } from 'lucide-react'
import { IconBadge, Method, Outcome, Reconstruction, SceneHeader, type SceneProps } from './scene-primitives'

export function DeliveryScene({ item, language }: SceneProps) {
  const t=translate(language)
  const [selected,setSelected]=useState(1)
  const details=[t('Требования, стоимость, сроки и критерии приёмки согласованы в ТЗ.','Requirements, cost, timing, and acceptance criteria are aligned in the brief.'),t('Контрольные точки помогают видеть ход работы и изменения объёма.','Checkpoints make progress and scope changes visible.'),t('Правки и разногласия согласуются с учётом бюджета, качества и сроков.','Revisions and disagreements are resolved against budget, quality, and timing.'),t('Передача материалов, платежи и закрывающие документы завершают цикл.','Material handoff, payments, and closing documents complete the cycle.')]

  const statuses=[t('ТЗ','Brief'),t('В работе','In progress'),t('Проверка','Review'),t('Передано','Delivered')]
  const stages=[[Search,t('Отбор','Select')],[ClipboardList,t('ТЗ','Brief')],[Handshake,t('Условия','Align')],[Settings2,t('Контроль','Check')],[GitPullRequest,t('Правки','Review')],[Send,t('Передача','Deliver')]] as const
  return <article className="case-scene delivery-scene"><div className="delivery-editorial"><SceneHeader item={item} language={language} role={t('операционная координация: от отбора до закрывающих документов', 'operations coordination: from selection through closing documents')}/><div className="delivery-proof"><span>{t('до','up to')}</span><strong className="scene-number">8</strong><p>{t('подрядчиков одновременно','contractors at the same time')}</p></div><Outcome label={t('Что стало управляемым','What became manageable')}>{item.result[language]}</Outcome></div>
      <div className="delivery-system"><div className="scene-system-label"><Network size={19}/>{t('Система координации','Coordination system')}</div><div className="delivery-network"><svg viewBox="0 0 500 300" preserveAspectRatio="none" aria-hidden="true"><path d="M90 45 L180 45 L180 150 L320 150 L320 45 L410 45 M90 115 L180 115 M90 185 L180 185 L180 150 M90 255 L180 255 L180 185 M410 115 L320 115 M410 185 L320 185 L320 150 M410 255 L320 255 L320 185"/></svg><div className="delivery-hub"><IconBadge icon={Network}/><strong>{t('Общие правила','Shared rules')}</strong><span>{t('ТЗ · сроки · критерии','Briefs · timing · criteria')}</span></div>{Array.from({length:8},(_,i)=><button type="button" key={i} aria-label={`${t('Исполнитель','Supplier')} ${i+1}: ${statuses[i%4]}`} aria-pressed={selected===i} aria-controls="delivery-detail" onClick={()=>setSelected(i)} className={`delivery-node node-${i} scene-enter`} style={delay(.3+(i%4)*.1)}><span>{String(i+1).padStart(2,'0')}</span><div><small>{t('Исполнитель','Supplier')}</small><p><i className={i%4===3?'complete':''}/>{statuses[i%4]}</p></div>{i%4===3&&<Check size={15}/>}</button>)}</div><div id="delivery-detail" className="delivery-detail" aria-live="polite"><strong>{String(selected+1).padStart(2,'0')} / {statuses[selected%4]}</strong><p>{details[selected%4]}</p></div><p className="scene-footnote">{t('Условные статусы показывают принцип координации, не реальную загрузку.', 'Illustrative statuses explain coordination, not actual workloads.')}</p></div>
      <div className="delivery-pipeline">{stages.map(([Icon,label],i)=><div key={label} className="scene-enter" style={delay(.8+i*.07)}><Icon size={21} aria-hidden="true"/><span>{label}</span></div>)}</div><Method item={item} language={language} icons={[Search, FileCheck2, Handshake]}/><Reconstruction language={language}/>
    </article>
}
