import { delay, translate } from './scene-utils'
import { useState } from 'react'
import { ArrowRight, CircleCheck, Clock3, Database, Filter, Gauge, GitBranch, ListChecks, MessageSquare, ShieldCheck } from 'lucide-react'
import { IconBadge, Reconstruction, SceneHeader, type SceneProps } from './scene-primitives'

export function KpiScene({ item, language }: SceneProps) {
  const t=translate(language)
  const [selected,setSelected]=useState(0)
  const explanations=[t('Сроки: отделить личный результат от задержек на смежных этапах.','Timeliness: separate individual results from delays in adjacent stages.'),t('Качество: зафиксировать критерии оценки результата.','Quality: define the criteria for assessing outcomes.'),t('Объём: учитывать нагрузку вместе с качеством и сроками.','Volume: consider workload alongside quality and timing.'),t('Приоритеты: учитывать срочные задачи и дополнительную нагрузку.','Priorities: account for urgent tasks and additional workload.'),t('Внешние зависимости: учитывать отдельно, не приписывать сотруднику чужой результат.','External dependencies: consider separately; do not attribute others’ outcomes to the employee.')]

  return <article className={`case-scene kpi-scene ${selected===4?'is-external':'is-controlled'}`}>
    <SceneHeader item={item} language={language} role={t('полностью разработала системы для дизайна и контента и складского блока', 'fully designed the systems for design and content and the warehouse unit')}/>
    <div className="kpi-proof"><span className="scene-number">2</span><div><h4>{t('системы оценки работы','performance assessment systems')}</h4><p>{t('Ещё в двух блоках помогала: логистика и финансы.', 'Also contributed to two other units: logistics and finance.')}</p></div></div>
    <div className="kpi-engine">
      <div className="kpi-input"><p className="case-eyebrow">{t('Выберите показатель ↓', 'Choose a factor ↓')}</p>{[[Clock3,t('Сроки своей работы','Timing of own work')],[ShieldCheck,t('Качество результата','Quality of output')],[Gauge,t('Объём работы','Volume of work')],[ListChecks,t('Приоритеты и срочные задачи','Priorities and urgent tasks')],[GitBranch,t('Задержки других участников','Delays from other participants')]].map(([Icon,label],i)=>{const I=Icon as typeof Clock3;return <button type="button" aria-pressed={selected===i} onClick={()=>setSelected(i)} aria-controls="kpi-explanation" key={String(label)} className={`kpi-factor ${i===4?'external':''}`} style={delay(.25+i*.07)}><I size={18} aria-hidden="true"/><span>{String(label)}</span><ArrowRight size={15} aria-hidden="true"/></button>})}</div>
      <div className="kpi-filter"><div className="kpi-filter-core scene-enter" style={delay(.55)}><IconBadge icon={Filter}/><h4>{t('Может ли сотрудник влиять на результат?', 'Can the employee influence the outcome?')}</h4><span className="kpi-route-answer" key={selected}>{selected===4?t('Нет → учитываем отдельно', 'No → consider separately'):t('Проверяем личный вклад →', 'Check individual contribution →')}</span></div><div className="kpi-external scene-enter" style={delay(.85)}><GitBranch size={19} aria-hidden="true"/><p>{t('Контекст работы', 'Work context')}<small>{t('Чужую задержку нельзя приписать сотруднику.', 'Another person’s delay cannot be attributed to the employee.')}</small></p></div></div>
      <div className="kpi-model scene-enter" style={delay(1)}><div className="scene-system-label"><CircleCheck size={18}/>{t('KPI-модель', 'KPI model')}</div><h4>{t('За что оцениваем сотрудника', 'What the employee is assessed on')}</h4><ul>{[t('Что зависит от человека','What depends on the person'),t('Откуда берём данные','Where the data comes from'),t('Как рассчитываем оценку','How the assessment is calculated')].map(x=><li key={x}><CircleCheck size={18}/>{x}</li>)}</ul><div className="kpi-model-footer"><Database size={20}/><span>{t('Понятный расчёт и пояснения', 'Clear calculations and explanations')}</span></div></div>
    </div>
    <div id="kpi-explanation" className="kpi-explanation" aria-live="polite"><Filter size={20} aria-hidden="true"/><p>{explanations[selected]}</p><span>{t('Выберите фактор ↑','Select a factor ↑')}</span></div>
    <p className="scene-contribution"><MessageSquare size={20} aria-hidden="true"/>{t('Исследовала процессы и провела интервью. Проработала расчёты, ограничения переменной части и источники данных.', 'Researched processes and interviewed the team. Developed calculations, variable-pay constraints, and data sources.')}</p><Reconstruction language={language}/>
  </article>
}
