import { useState } from 'react'
import { ArrowRight, Bell, Check, Database, FileText, Folder, FolderTree, LockKeyhole, UserRound, Workflow, Zap } from 'lucide-react'
import type { Language } from '@/hooks/use-language'
import { delay, translate } from './scene-utils'
import { IconBadge } from './scene-primitives'

export function MoreScene({ language }: { language: Language }) {
  const t = translate(language)
  const [released, setReleased] = useState(false)
  return <article className="case-scene epilogue-scene">
    <header className="scene-header"><p className="case-eyebrow">MORE / {t('Ещё четыре решения', 'Four more solutions')}</p><h3>{t('Меньше ручной координации', 'Less manual coordination')}</h3><p className="scene-lead">{t('Автоматизировала повторяемое. Сделала понятными доступ, состояние материалов и хранение.', 'Automated repeatable work. Made access, material status, and storage easier to manage.')}</p></header>
    <div className="epilogue-grid">
      <section className="micro-case micro-automation scene-enter" style={delay(.2)}><header><IconBadge icon={Workflow}/><div><span className="case-eyebrow">Bitrix24</span><h4>{t('Действие — по правилу', 'Actions follow rules')}</h4></div></header><div className="automation-story"><div><span className="micro-state"><Zap size={16}/>{t('Событие', 'Event')}</span><strong>{t('Сработал триггер', 'A trigger fires')}</strong></div><ArrowRight aria-hidden="true"/><div className="automation-rule"><Workflow size={25}/><strong>{t('Робот выполняет сценарий', 'Automation runs the rule')}</strong></div><ArrowRight aria-hidden="true"/><Bell className="automation-bell" size={27} aria-label={t('Уведомление', 'Notification')}/></div><p>{t('Настраивала смарт-процессы, роботов и триггеры: статусы и уведомления связывались в автоматические сценарии.', 'Configured smart processes, automation rules, and triggers, connecting statuses and notifications into automated flows.')}</p><footer>{t('Ручные операции → повторяемая автоматизация', 'Manual operations → repeatable automation')}</footer></section>
      <section className="micro-case micro-resource scene-enter" style={delay(.3)}><header><IconBadge icon={LockKeyhole}/><div><span className="case-eyebrow">{t('Общий ресурс', 'Shared resource')}</span><h4>{t('Доступ без координатора', 'Access without a coordinator')}</h4></div></header><div className={`resource-demo ${released?'is-released':''}`}><div className="resource-waiting"><UserRound size={21}/><span>{t('Следующий в очереди', 'Next in the queue')}</span></div><ArrowRight size={22} aria-hidden="true"/><button type="button" onClick={()=>setReleased(!released)} aria-label={released?t('Повторить передачу доступа', 'Replay access handoff'):t('Показать освобождение ресурса', 'Show resource release')}><LockKeyhole size={19}/><span>{released?t('Доступ передан', 'Access transferred'):t('Освободить ресурс', 'Release resource')}</span></button></div><div className="resource-message" aria-live="polite"><Bell size={16}/>{released?t('Следующий пользователь получил уведомление.', 'The next user receives a notification.'):t('Освобождение → уведомление следующему.', 'Release → notify the next user.')}</div><footer><strong>−50%</strong><span>{t('конфликтов и повторных уточнений', 'conflicts and repeat checks')}<small>{t('Несколько часов команды в неделю сэкономлено', 'Several team hours saved each week')}</small></span></footer></section>
      <section className="micro-case micro-registry scene-enter" style={delay(.4)}><header><IconBadge icon={Database}/><div><span className="case-eyebrow">{t('Реестр контента', 'Content registry')}</span><h4>{t('Видно, что с материалами', 'See where materials stand')}</h4></div></header><div className="registry-story"><div><strong className="scene-number">20+</strong><span>{t('товарных позиций', 'product positions')}</span></div><div className="registry-sheet"><span><FileText size={16}/>{t('Материал', 'Material')}</span><ArrowRight size={16}/><span>{t('Статус', 'Status')}</span><ArrowRight size={16}/><span><Check size={16}/>{t('Готовность', 'Readiness')}</span></div></div><p>{t('Собрала состояние материалов, статусы и готовность в одной точке контроля.', 'Brought material status and readiness into one control point.')}</p><footer>{t('Меньше ручных сверок и риска пропусков', 'Fewer manual checks and less risk of omissions')}</footer></section>
      <section className="micro-case micro-storage scene-enter" style={delay(.5)}><header><IconBadge icon={FolderTree}/><div><span className="case-eyebrow">{t('Внутреннее хранилище', 'Internal storage')}</span><h4>{t('Найти. Понять. Передать.', 'Find it. Understand it. Share it.')}</h4></div></header><div className="storage-story"><div><Folder size={30}/><strong>{t('Рабочая информация', 'Working information')}</strong></div><ul>{[t('Понятная структура и названия', 'Clear structure and names'),t('Правила доступа', 'Access rules'),t('Передача и архив', 'Handoffs and archive')].map(x=><li key={x}><Folder size={16}/>{x}</li>)}</ul></div><p>{t('Спроектировала архитектуру хранения и правила работы с файлами.', 'Designed the storage architecture and rules for working with files.')}</p><footer>{t('Меньше дублей, проще найти нужное', 'Fewer duplicates; easier retrieval')}</footer></section>
    </div><p className="scene-footnote">{t('Схемы показывают принцип работы; это не внутренние интерфейсы.', 'Diagrams explain the approach; these are not internal interfaces.')}</p>
  </article>
}
