import { Bell, Check, Database, FolderTree, GitBranch, LockKeyhole, Workflow, Zap } from 'lucide-react'
import type { Language } from '@/hooks/use-language'
import { delay, translate } from './scene-utils'
import { IconBadge } from './scene-primitives'

export function MoreScene({ language }: { language: Language }) {
  const t = translate(language)
  return <article className="case-scene more-scene more-four">
    <header className="scene-header"><p className="case-eyebrow">{t('Дополнительные системы', 'Additional systems')} / MORE</p><h3>{t('Ещё внедрила', 'Also implemented')}</h3><p className="scene-lead">{t('Четыре решения для автоматизации, контроля и доступа к рабочей информации.', 'Four solutions for automation, control, and access to working information.')}</p></header>
    <div className="more-grid">
      <section className="more-mini scene-enter" style={delay(.25)}><header><IconBadge icon={Workflow}/><h4>{t('Автоматизация в Bitrix24', 'Bitrix24 automation')}</h4></header><div className="mini-automation" aria-hidden="true"><span><GitBranch size={19}/>{t('Триггер', 'Trigger')}</span><i>→</i><span><Zap size={19}/>{t('Робот', 'Robot')}</span><i>→</i><span><Bell size={19}/>{t('Сценарий', 'Scenario')}</span></div><p>{t('Переводила ручные операции в смарт-процессы: роботы, триггеры, статусы и уведомления.', 'Turned manual operations into smart processes with automation rules, triggers, statuses, and notifications.')}</p><footer>{t('Повторяемая работа выполняется по сценарию', 'Repeatable work follows an automated flow')}</footer></section>
      <section className="more-mini scene-enter" style={delay(.35)}><header><IconBadge icon={LockKeyhole}/><h4>{t('Self-service доступ', 'Self-service access')}</h4></header><div className="mini-access"><span>{t('Очередь', 'Queue')}</span><i aria-hidden="true">→</i><span>{t('Статус', 'Status')}</span><i aria-hidden="true">→</i><span>{t('Освобождение', 'Release')}</span><Bell aria-label={t('Уведомление следующему', 'Notify the next user')} size={19}/></div><p>{t('Заменила ручную координацию очередью, освобождением ресурса и уведомлением следующего пользователя.', 'Replaced manual coordination with a queue, resource release, and notification of the next user.')}</p><footer><strong>÷2</strong>{t('конфликтов и повторных уточнений; несколько часов команды в неделю сэкономлено', 'conflicts and repeat checks; several team hours saved each week')}</footer></section>
      <section className="more-mini scene-enter" style={delay(.45)}><header><IconBadge icon={Database}/><h4>{t('Реестр контента', 'Content registry')}</h4></header><div className="mini-registry" aria-hidden="true">{[t('Материалы', 'Materials'),t('Статусы', 'Statuses'),t('Готовность', 'Readiness')].map(label=><span key={label}><Check size={15}/>{label}</span>)}</div><p>{t('Создала единую точку контроля состояния материалов, статусов и готовности для 20+ товарных позиций.', 'Created one control point for material status and readiness across 20+ product positions.')}</p><footer>{t('Меньше ручных сверок и риска пропусков', 'Fewer manual checks and less risk of omissions')}</footer></section>
      <section className="more-mini scene-enter" style={delay(.55)}><header><IconBadge icon={FolderTree}/><h4>{t('Архитектура хранилища', 'Storage architecture')}</h4></header><div className="mini-storage" aria-hidden="true"><span>{t('Рабочие материалы', 'Working materials')}</span><div><span>{t('Именование', 'Naming')}</span><span>{t('Доступы', 'Access')}</span><span>{t('Архив', 'Archive')}</span></div></div><p>{t('Спроектировала структуру, правила именования, доступа и передачи рабочей информации.', 'Designed the structure, naming, access, and handoff rules for working information.')}</p><footer>{t('Меньше дублей, проще найти и передать материалы', 'Fewer duplicates; easier retrieval and handoffs')}</footer></section>
    </div><p className="scene-footnote">{t('Схемы реконструированы, внутренние данные не используются.', 'Reconstructed diagrams; no internal data is used.')}</p>
  </article>
}
